services:
#  Optional
  alfresco-dockia-agents-share:
    image: ${docker.share.image}:${alfresco.share.version}
    environment:
      REPO_HOST: alfresco-dockia-agents-acs
      REPO_PORT: 8080
    ports:
      - "${share.port}:8080"
  alfresco-dockia-agents-acs:
    image: alfresco-content-services-alfresco-dockia-agents:development
    build:
      dockerfile: ./Dockerfile
      context: ../../../target
    environment:
      JAVA_TOOL_OPTIONS: "${keystore.settings}"
      JAVA_OPTS: "
        -Dsolr.secureComms=secret
        -Dsolr.sharedSecret=secret
        -Dmessaging.broker.url=\"failover:(nio://alfresco-dockia-agents-activemq:61616)?timeout=3000&jms.useCompression=true\"
        "
      CATALINA_OPTS: "-agentlib:jdwp=transport=dt_socket,server=y,suspend=n,address=0.0.0.0:8888"
    ports:
      - "${acs.port}:8080"
      - "${acs.debug.port}:8888"
    volumes:
      - alfresco-dockia-agents-acs-volume:/usr/local/tomcat/alf_data
      - /var/run/docker.sock:/var/run/docker.sock
    depends_on:
      - alfresco-dockia-agents-postgres
  alfresco-dockia-agents-postgres:
    image: postgres:16.5
    environment:
      POSTGRES_DB: alfresco
      POSTGRES_USER: alfresco
      POSTGRES_PASSWORD: alfresco
    command: postgres -c max_connections=300 -c log_min_messages=LOG
    ports:
      - "${postgres.port}:5432"
    volumes:
      - alfresco-dockia-agents-db-volume:/var/lib/postgresql/data
  alfresco-dockia-agents-ass:
    image: alfresco/alfresco-search-services:2.0.15
    environment:
      SOLR_ALFRESCO_HOST: alfresco-dockia-agents-acs
      SOLR_ALFRESCO_PORT: 8080
      SOLR_SOLR_HOST: alfresco-dockia-agents-ass
      SOLR_SOLR_PORT: 8983
      SOLR_CREATE_ALFRESCO_DEFAULTS: alfresco,archive
      ALFRESCO_SECURE_COMMS: "secret"
      JAVA_TOOL_OPTIONS: "-Dalfresco.secureComms.secret=secret"
    ports:
      - "8983:8983"
    volumes:
      - alfresco-dockia-agents-ass-volume:/opt/alfresco-search-services/contentstore
      - alfresco-dockia-agents-ass-volume:/opt/alfresco-search-services/data
  alfresco-dockia-agents-activemq:
      image: alfresco/alfresco-activemq:5.18-jre17-rockylinux8
      mem_limit: 1g
      ports:
        - 8161:8161 # Web Console
        - 5672:5672 # AMQP
        - 61616:61616 # OpenWire
        - 61613:61613 # STOMP

volumes:
  alfresco-dockia-agents-acs-volume:
    external: true
  alfresco-dockia-agents-db-volume:
    external: true
  alfresco-dockia-agents-ass-volume:
    external: true
